import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from "../../public/images/profile/prueba2.png"
import AnimatedText from '@/components/animatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image src={profilePic} alt="Roxy Pérez" className="w-full h-auto rounded-lg">
              </Image>
            </div>
            <div className="w-1/2 flex-col items-center self-center" >
              <AnimatedText text="FullStack Developer: Creando soluciones web de principio a fin. </>" className='!text-[3.75rem] !text-left' />
              <p>Como desarrolladora full-stack, me dedico a convertir ideas en aplicaciones web innovadoras de una manera simple y creativa.
                Explore mis últimos proyectos y mis habilidades, mostrando mi experiencia en Angular, base de datos y desarrollo web.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href="/2023-RoxyPerezCV.pdf" target='_blank'
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                  border-2 border-solid border-transparent hover:border-dark hover:text-primaryDark hover:bg-light'
                  download={true}>Curriculum<LinkArrow className={'w-6 m1-1'} /></Link>
                <Link href="mailto:necropsia32@gmail.com" target='_blank' className='ml-4 text-lg font-medium capitalize text-dark underline hover:text-primary'>Contacto</Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
